apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
data:
  secretkey: YWI4eFA3UjlPdlVBV0w4VmUxWUdzaU5CTHRoSWkwTnRkaWQwS3pVb0JXU2pMcnRFNGFpUXZKVXhtc0tLMHBmdgpWR01Lb3ZBUE5QOUs4MGcvVjJBenZnSDhDb0ZmVGRIRUhYbXNCNnMvNkxKWmdaeFZSNzIzZkZoeWFmMWhrQVJyCkNPZXZTdS8vZkVtZnhvaDlvWXQ4QnRTbEc5TlcveEdRVmVkbndsSHU5Ulk9
